### ISSUE TITLE
[1.16.3 ][ftb-chunks-1603.2.0.42] Mod prevents world from being deleted

### ISSUE THREAD

**Issue by LuciusV** [FTBTeam/FTB-Chunks#50] opened 2020-11-06 06:36 UTC
IF I exit to main main menu and try to delete world, 'ftbchunks' folder in save can't be deleted and therefore does not let to delete world, resulting in delete failed message.

**Comment by Ozzymud** [comment] 2021-02-16 23:54
Just wanted to chime in that this is still an issue. Using ftb-chunks-1604.2.2.62 in the Sky Bees modpack. When trying to access the folder directly I see this:

![image1](https://user-images.githubusercontent.com/6426344/108136369-c9d7ab00-706e-11eb-90b1-cb3a73f32fa4.png)

**Comment by MaxNeedsSnacks** [comment] 2021-03-12 14:03
Duplicate of #39, it's been fixed in newer versions

**Closed by MaxNeedsSnacks** 2021-03-12 14:03 UTC
