### ISSUE TITLE
[Suggestion] Hide Player Head on the minimap when the player has invisibility effect

### ISSUE THREAD

**Issue by Asveste** [FTBTeam/FTB-Chunks#107] opened 2021-02-09 02:26 UTC
Yeah, the title says everything. Would be cool if theres a config for that or something similar.

**Comment by Asveste** [comment] 2021-02-09 05:06
Addition: Twilight Cloak from Reliquary should also be included

**Comment by MaxNeedsSnacks** [comment] 2021-03-12 15:25
Duplicate of #93

**Closed by MaxNeedsSnacks** 2021-03-12 15:25 UTC
