### ISSUE TITLE
[Bug 1.16.4] item user from cyclic won't work in claimed chunks when on a server

### ISSUE THREAD

**Issue by mthnry** [FTBTeam/FTB-Chunks#86] opened 2021-01-08 22:02 UTC
If on a server cyclic's item user won't place aquamarine in a lightwell when placed in a claimed or force-loaded chunk. As soon as you unclaim the chunks, the item user starts working.
Seems like it is seen as another player and though prevented to interact in claimed chunks.

Versions tested:

cyclic 0.10.1 and 1.1.0
ftb-chunks 1604.2.2.53

Both being part of the Direwolf20 modpack for 1.16.

**Comment by LezChap** [comment] 2021-01-13 17:37
This may be a Astral conflict...as it effects the Lightwell with other "fake player" as well.  (I tried Modular Routers.)  

It only seems to impact servers (SMP), and seems works as expected in Single Player.  

Friending the Fake Player in the GUI did not solve the problem either.

**Comment by mthnry** [comment] 2021-01-13 18:54
I added the fake player in FTB chunks later on and that made it work. There are as much fake players as you placed item users though. Don't know if that's from cyclic or FTB chunks.

**Comment by LezChap** [comment] 2021-01-13 19:23
I'll re-test that next time I'm playing...It didn't work for me and the modular router, but maybe I did something wrong with the friend gui.

**Comment by MaxNeedsSnacks** [comment] 2021-03-12 15:11
Duplicate of #59

**Closed by MaxNeedsSnacks** 2021-03-12 15:11 UTC

**Comment by dark2phoenix** [comment] 2021-04-12 13:01
I still think there is something wrong here.  When I placed the user in a chunk that was already claimed, the item user wouldn't work.  However, if I unclaimed the chunk, placed the user it works and continues to work after I claim the chunk.  If I break it and replace it, doesn't work until I unclaim the chunk and replace it. 

I'm using the DW20 1.16 v1.70
