### ISSUE TITLE
worlds unable to delete 1.16.4/5

### ISSUE THREAD

**Issue by redo6565** [FTBTeam/FTB-Chunks#103] opened 2021-02-01 21:25 UTC
Failed to delete world New World
java.nio.file.AccessDeniedException: D:\Twitch\Minecraft\Instances\almost vanilla\saves\New World\data\ftbchunks
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:83)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsDirectoryStream.<init>(WindowsDirectoryStream.java:86)
	at sun.nio.fs.WindowsFileSystemProvider.newDirectoryStream(WindowsFileSystemProvider.java:518)
	at java.nio.file.Files.newDirectoryStream(Files.java:457)
	at java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
	at java.nio.file.FileTreeWalker.next(FileTreeWalker.java:372)
	at java.nio.file.Files.walkFileTree(Files.java:2706)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at net.minecraft.world.storage.SaveFormat$LevelSave.func_237299_g_(SaveFormat.java:377)
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry.func_214440_b(SourceFile:329)
	at net.minecraft.client.gui.screen.WorldSelectionList$Entry$$Lambda$18776/398480193.accept(Unknown Source)
	at net.minecraft.client.gui.screen.ConfirmScreen.func_213002_b(SourceFile:41)
	at net.minecraft.client.gui.screen.ConfirmScreen$$Lambda$18778/974233529.onPress(Unknown Source)
	at net.minecraft.client.gui.widget.button.Button.func_230930_b_(SourceFile:33)
	at net.minecraft.client.gui.widget.button.AbstractButton.func_230982_a_(SourceFile:16)
	at net.minecraft.client.gui.widget.Widget.func_231044_a_(Widget.java:136)
	at net.minecraft.client.gui.INestedGuiEventHandler.func_231044_a_(SourceFile:27)
	at net.minecraft.client.MouseHelper.lambda$mouseButtonCallback$0(MouseHelper.java:87)
	at net.minecraft.client.MouseHelper$$Lambda$18712/964797618.run(Unknown Source)
	at net.minecraft.client.gui.screen.Screen.func_231153_a_(Screen.java:427)
	at net.minecraft.client.MouseHelper.func_198023_a(MouseHelper.java:85)
	at net.minecraft.client.MouseHelper.lambda$null$4(MouseHelper.java:175)
	at net.minecraft.client.MouseHelper$$Lambda$18711/1036492493.run(Unknown Source)
	at net.minecraft.util.concurrent.ThreadTaskExecutor.execute(SourceFile:94)
	at net.minecraft.client.MouseHelper.lambda$registerCallbacks$5(MouseHelper.java:174)
	at net.minecraft.client.MouseHelper$$Lambda$15322/1862734759.invoke(Unknown Source)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174)
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(SourceFile:127)
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:999)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607)
	at net.minecraft.client.main.Main.main(Main.java:184)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$480/295372946.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
16:16:03.802
Stopping!

**Comment by Rensik** [comment] 2021-02-07 17:20
Something FTB Chunks does locks world folders in single player so that they can't be deleted while the game is running.

**Comment by MaxNeedsSnacks** [comment] 2021-03-12 15:23
Duplicate of #39

**Closed by MaxNeedsSnacks** 2021-03-12 15:23 UTC
